default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: hello
  password: 123456
  host: localhost
  port: 5000

development:
  <<: *default
  database: hello_world_rails_development
test:
  <<: *default
  database: hello_world_rails_test
production:
  <<: *default
  database: hello_world_rails_production
  username: hello_world_rails
  password: <%= ENV['HELLO_WORLD_RAILS_DATABASE_PASSWORD'] %>
